### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by 779257747** [OpenBMB/AgentVerse#102]
今天新拉了一下代码，想自定义环境报错，看样子是自定义任务的目录没找到，但是已经在tasksolving的文件夹中了
：
Traceback (most recent call last):
  File "/Users/yaoxingzhi/opt/anaconda3/envs/agentverse/bin/agentverse-tasksolving", line 8, in <module>
    sys.exit(cli_main())
  File "/Users/yaoxingzhi/opt/anaconda3/envs/agentverse/lib/python3.10/site-packages/agentverse_command/main_tasksolving_cli.py", line 29, in cli_main
    agentversepipeline = TaskSolving.from_task(args.task, args.tasks_dir)
  File "/Users/yaoxingzhi/opt/anaconda3/envs/agentverse/lib/python3.10/site-packages/agentverse/tasksolving.py", line 32, in from_task
    task_config = prepare_task_config(task, tasks_dir)
  File "/Users/yaoxingzhi/opt/anaconda3/envs/agentverse/lib/python3.10/site-packages/agentverse/initialization.py", line 88, in prepare_task_config
    raise ValueError(f"Task {task} not found. Available tasks: {all_tasks}")
ValueError: Task __pycache__ not found. Available tasks: ['tasksolving', 'tasksolving/mgsm', 'tasksolving/tool_using', 'tasksolving/humaneval', 'tasksolving/responsegen', 'tasksolving/commongen', 'tasksolving/brainstorming', 'tasksolving/logic_grid', 'tasksolving/pythoncalculator', 'simulation', 'simulation/nlp_classroom_9players_group', 'simulation/nlp_classroom_3players', 'simulation/pokemon', 'simulation/nlp_classroom_9players', 'simulation/prisoner_dilemma', 'simulation/nlp_classroom_3players_withtool', 'simulation/sde_team', 'simulation/alice_home', 'simulation/db_diag', 'simulation/math_problem_2players_tools']

**Comment by chenweize1998** [comment]
试试指定参数`--tasks_dir`，例如`--tasks_dir /my/path/to/AgentVerse/agentverse/tasks`. 

另外，是不是你新拉的代码和你原来执行`pip install -e .`的代码位置不一样（比如你新开了一个文件夹来拉新代码）？如果是的话，要重新在新代码的位置`pip install -e .`

**Comment by 779257747** [comment]
好的谢谢
