### ISSUE TITLE
Error message is logged: RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by Ytang520** [OpenBMB/AgentVerse#139]
I recently ran into the same error #128 when implementing the example command provided:
`agentverse-benchmark --task tasksolving/humaneval/gpt-3.5 --dataset_path data/humaneval/test.jsonl --overwrite
`
Are there any updates to the code regarding asynchronous operations? I am new to this concept and am unsure if this error will cause unexpected results. Can I ignore this error? Or are there any suggestions for fixing the problematic part of the code? I’ve read the previous response #128, but I’m still unable to locate the exact position of the error in order to fix it.

Also, just to check - is there a report of computed results like pass@1 on the Humaneval dataset? I have run some lines and only gotten logs and individual results for different questions…

---
## Log:
Role Assignment:
a mathematician specializing in numerical analysis
a computer scientist with expertise in algorithms and data structures  
Initial Plan:
    return number - int(number)
  
Task exception was never retrieved
future: <Task finished name='Task-29' coro=<AsyncClient.aclose() done, defined at D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\site-packages\httpx\_client.py:1967> exception=RuntimeError('Event loop is closed')>
Traceback (most recent call last):
  File "D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\site-packages\httpx\_client.py", line 1974, in aclose
    await self._transport.aclose()
  File "D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\site-packages\httpx\_transports\default.py", line 378, in aclose
    await self._pool.aclose()
  File "D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\site-packages\httpcore\_async\connection_pool.py", line 314, in aclose
    await connection.aclose()
  File "D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\site-packages\httpcore\_async\connection.py", line 173, in aclose
    await self._connection.aclose()
  File "D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\site-packages\httpcore\_async\http11.py", line 253, in aclose 
    await self._network_stream.aclose()
  File "D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\site-packages\httpcore\_backends\anyio.py", line 54, in aclose    await self._stream.aclose()
  File "D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\site-packages\anyio\_backends\_asyncio.py", line 1202, in aclose
    self._transport.close()
  File "D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\asyncio\proactor_events.py", line 109, in close
    self._loop.call_soon(self._call_connection_lost, None)  
  File "D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\asyncio\base_events.py", line 753, in call_soon
    self._check_closed()
  File "D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Task exception was never retrieved
future: <Task finished name='Task-30' coro=<AsyncClient.aclose() done, defined at D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\site-packages\httpx\_client.py:1967> exception=RuntimeError('Event loop is closed')>
Traceback (most recent call last):
  File "D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\site-packages\httpx\_client.py", line 1974, in aclose
    await self._transport.aclose()
  File "D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\site-packages\httpx\_transports\default.py", line 378, in aclose
    await self._pool.aclose()
  File "D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\site-packages\httpcore\_async\connection_pool.py", line 314, in aclose
    await connection.aclose()
  File "D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\site-packages\httpcore\_async\connection.py", line 173, in aclose
    await self._connection.aclose()
  File "D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\site-packages\httpcore\_async\http11.py", line 253, in aclose 
    await self._network_stream.aclose()
  File "D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\site-packages\httpcore\_backends\anyio.py", line 54, in aclose    await self._stream.aclose()
  File "D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\site-packages\anyio\_backends\_asyncio.py", line 1202, in aclose
    self._transport.close()
  File "D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\asyncio\proactor_events.py", line 109, in close
    self._loop.call_soon(self._call_connection_lost, None)  
  File "D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\asyncio\base_events.py", line 753, in call_soon
    self._check_closed()
  File "D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Task exception was never retrieved
future: <Task finished name='Task-31' coro=<AsyncClient.aclose() done, defined at D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\site-packages\httpx\_client.py:1967> exception=RuntimeError('Event loop is closed')>
Traceback (most recent call last):
  File "D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\site-packages\httpx\_client.py", line 1974, in aclose
    await self._transport.aclose()
  File "D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\site-packages\httpx\_transports\default.py", line 378, in aclose
    await self._pool.aclose()
  File "D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\site-packages\httpcore\_async\connection_pool.py", line 314, in aclose
    await connection.aclose()
  File "D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\site-packages\httpcore\_async\connection.py", line 173, in aclose
    await self._connection.aclose()
  File "D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\site-packages\httpcore\_async\http11.py", line 253, in aclose 
    await self._network_stream.aclose()
  File "D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\site-packages\httpcore\_backends\anyio.py", line 54, in aclose    await self._stream.aclose()
  File "D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\site-packages\anyio\_backends\_asyncio.py", line 1202, in aclose
    self._transport.close()
  File "D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\asyncio\proactor_events.py", line 109, in close
    self._loop.call_soon(self._call_connection_lost, None)  
  File "D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\asyncio\base_events.py", line 753, in call_soon
    self._check_closed()
  File "D:\Users\Lenovo\anaconda3\envs\agentverse_env\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Reviews:
[a computer scientist with expertise in algorithms and data 
structures]:   
Consensus Reached!. 
Decision Plan:
    return number - int(number)
  
Execution Result: 
 
Evaluation result:
Score: True
Advice: The provided solution is correct. However, it would 
be beneficial to add some comments to explain the logic behind the code. In the next round, recruiting a software engineer with experience in code documentation and best practices 
could be helpful.  
Good score! Accept! Final Result:
    return number - int(number)

**Comment by chenweize1998** [comment]
Hi, sorry for the late reply. Could you try downgrading `openai` to version 1.1.0 by `pip install openai==1.1.0`? That version works for me and currently I don't see the error message again.
