### ISSUE TITLE
error:subprocess-exited-with-error

### ISSUE THREAD

**Issue by JunmingRen** [OpenBMB/AgentVerse#142]
when i try to "pip install -r requirements.txt",  i got the following error:
subprocess.CalledProcessError: Command '['meson', 'setup', '--native-file=/tmp/pip-install-o31kknot/scipy_1afa3cdb99b746f5a5d8988b069a1481/.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2', '--prefix=/mnt/data/mingjun/anaconda3', '/tmp/pip-install-o31kknot/scipy_1afa3cdb99b746f5a5d8988b069a1481', '/tmp/pip-install-o31kknot/scipy_1afa3cdb99b746f5a5d8988b069a1481/.mesonpy-c47lm_0d/build']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

**Comment by downing777** [comment]
Hi, I got similar errors when I try 'pip install -e .'
```Bash
Building wheels for collected packages: numpy
        Building wheel for numpy (setup.py): started
        Building wheel for numpy (setup.py): finished with status 'error'
        error: subprocess-exited-with-error
      
        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [15 lines of output]
            Running from numpy source directory.
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/private/var/folders/2h/fq3p7z3j28jcb6tmxr2w73wh0000gn/T/pip-install-kr1qh88j/numpy_e0ccf2c57e7947c08bcd09f06dcd60bd/setup.py", line 443, in <module>
                setup_package()
              File "/private/var/folders/2h/fq3p7z3j28jcb6tmxr2w73wh0000gn/T/pip-install-kr1qh88j/numpy_e0ccf2c57e7947c08bcd09f06dcd60bd/setup.py", line 422, in setup_package
                from numpy.distutils.core import setup
              File "/private/var/folders/2h/fq3p7z3j28jcb6tmxr2w73wh0000gn/T/pip-install-kr1qh88j/numpy_e0ccf2c57e7947c08bcd09f06dcd60bd/numpy/distutils/core.py", line 26, in <module>
                from numpy.distutils.command import config, config_compiler, \
              File "/private/var/folders/2h/fq3p7z3j28jcb6tmxr2w73wh0000gn/T/pip-install-kr1qh88j/numpy_e0ccf2c57e7947c08bcd09f06dcd60bd/numpy/distutils/command/config.py", line 20, in <module>
                from numpy.distutils.mingw32ccompiler import generate_manifest
              File "/private/var/folders/2h/fq3p7z3j28jcb6tmxr2w73wh0000gn/T/pip-install-kr1qh88j/numpy_e0ccf2c57e7947c08bcd09f06dcd60bd/numpy/distutils/mingw32ccompiler.py", line 34, in <module>
                from distutils.msvccompiler import get_build_version as get_build_msvc_version
            ModuleNotFoundError: No module named 'distutils.msvccompiler'
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
        Running setup.py clean for numpy
        error: subprocess-exited-with-error
      
        × python setup.py clean did not run successfully.
        │ exit code: 1
        ╰─> [10 lines of output]
            Running from numpy source directory.
      
            `setup.py clean` is not supported, use one of the following instead:
      
              - `git clean -xdf` (cleans all files)
              - `git clean -Xdf` (cleans all versioned files, doesn't touch
                                  files that aren't checked into the git repo)
      
            Add `--force` to your command to use it anyway if you must (unsupported).
      
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed cleaning build dir for numpy
      Failed to build numpy
      ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (numpy)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
Did you fix it ?
