### ISSUE TITLE
求助：运行demo出错

### ISSUE THREAD

**Issue by qiansheng2** [OpenBMB/AgentVerse#22]
安装后，出错信息如下：
请看看是什么问题导致的呢？

-> % python3 main.py --task nlp_classroom_9players                                  
will register chemical-prop
will register douban-film
will register wikidata
will register stock
will register weather
will register wikipedia
will register wolframalpha
will register office-ppt
will register bing_search
will register bing_map
will register baidu_map
will register nllb-translation
will register baidu-translation
will register tutorial
will register file_operation
will register meta_analysis
will register database
will register db_diag
will register code_interpreter
will register hugging_tools
will register arxiv
will register zillow
will register google_scholar
will register google_places
will register google_serper
will register python
will register sceneXplain
will register shell
will register image_generation
will register airbnb
will register job_search
will register gradio_tools
will register travel
will register walmart
Traceback (most recent call last):
  File "/Users/nick/personal/AgentVerse/main.py", line 4, in <module>
    from agentverse.agentverse import AgentVerse
  File "/Users/nick/personal/AgentVerse/agentverse/__init__.py", line 4, in <module>
    from .environments import env_registry
  File "/Users/nick/personal/AgentVerse/agentverse/environments/__init__.py", line 7, in <module>
    from .basic import BasicEnvironment
  File "/Users/nick/personal/AgentVerse/agentverse/environments/basic.py", line 6, in <module>
    from agentverse.agents.conversation_agent import BaseAgent
  File "/Users/nick/personal/AgentVerse/agentverse/agents/__init__.py", line 6, in <module>
    from .base import BaseAgent
  File "/Users/nick/personal/AgentVerse/agentverse/agents/base.py", line 8, in <module>
    from agentverse.memory import BaseMemory, ChatHistoryMemory
  File "/Users/nick/personal/AgentVerse/agentverse/memory/__init__.py", line 7, in <module>
    from .summary import SummaryMemory
  File "/Users/nick/personal/AgentVerse/agentverse/memory/summary.py", line 7, in <module>
    from agentverse.initialization import load_llm
  File "/Users/nick/personal/AgentVerse/agentverse/initialization.py", line 18, in <module>
    from agentverse.memory_manipulator import memory_manipulator_registry
  File "/Users/nick/personal/AgentVerse/agentverse/memory_manipulator/__init__.py", line 7, in <module>
    from .reflection import Reflection
  File "/Users/nick/personal/AgentVerse/agentverse/memory_manipulator/reflection.py", line 12, in <module>
    from sklearn.metrics.pairwise import cosine_similarity
ModuleNotFoundError: No module named 'sklearn'
(textgen) nick@nickmac [09时30分29秒] [~/personal/AgentVerse] [main]
-> % pip install sklearn                          
Requirement already satisfied: sklearn in /Users/nick/anaconda3/envs/textgen/lib/python3.10/site-packages (0.0.post7)

**Comment by qiansheng2** [comment]
我的环境是macos m1

**Comment by chenweize1998** [comment]
We missed the dependency on scikit-learn in our requirement. We will fix it soon. For you to fix the problem, simply install it using `pip install -U scikit-learn`
