### ISSUE TITLE
0.1.5报错ModuleNotFoundError: No module named 'agentverse.llms.utils'

### ISSUE THREAD

**Issue by weibinke** [OpenBMB/AgentVerse#60]
报错了，是不是没少提交了代码。

(.venv) ➜  AgentVerse git:(main) ✗ python agentverse_command/main_simulation_gui.py --task simulation/nlp_classroom_9players
Traceback (most recent call last):
  File "/Users/weibinke/ChatGPT/AgentVerse/agentverse_command/main_simulation_gui.py", line 2, in <module>
    from agentverse.gui import GUI
  File "/Users/weibinke/ChatGPT/AgentVerse/.venv/lib/python3.11/site-packages/agentverse/__init__.py", line 1, in <module>
    from .tasks import *
  File "/Users/weibinke/ChatGPT/AgentVerse/.venv/lib/python3.11/site-packages/agentverse/tasks/__init__.py", line 4, in <module>
    from .simulation.math_problem_2players_tools.output_parser import (
  File "/Users/weibinke/ChatGPT/AgentVerse/.venv/lib/python3.11/site-packages/agentverse/tasks/simulation/math_problem_2players_tools/output_parser.py", line 6, in <module>
    from agentverse.parser import OutputParserError, output_parser_registry, OutputParser
  File "/Users/weibinke/ChatGPT/AgentVerse/.venv/lib/python3.11/site-packages/agentverse/parser.py", line 4, in <module>
    from agentverse.llms.base import LLMResult
  File "/Users/weibinke/ChatGPT/AgentVerse/.venv/lib/python3.11/site-packages/agentverse/llms/__init__.py", line 6, in <module>
    from .openai import OpenAIChat
  File "/Users/weibinke/ChatGPT/AgentVerse/.venv/lib/python3.11/site-packages/agentverse/llms/openai.py", line 18, in <module>
    from agentverse.llms.utils.jsonrepair import JsonRepair
ModuleNotFoundError: No module named 'agentverse.llms.utils'

**Comment by chenweize1998** [comment]
Try installing the latest code in Github. We have fixed the bug and will upload a new version.
